### ISSUE TITLE
Empty page "Connected" specifically on ESP32

### ISSUE THREAD

**Issue by Looki2000** [s00500/ESPUI#317]
**Describe the bug**
I'm getting empty page with "Connected" on ESP32 WROOM 32D in both hotspot and regular mode.

Browser console shows this:
```controls.js:11 websock open
controls.js:60 Unknown type or event
handleEvent @ controls.js:60
controls.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at WebSocket.handleEvent (controls.js:35:75)
handleEvent @ controls.js:35
controls.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at WebSocket.handleEvent (controls.js:35:75)
handleEvent @ controls.js:35
controls.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at WebSocket.handleEvent (controls.js:35:75)
handleEvent @ controls.js:35
controls.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at WebSocket.handleEvent (controls.js:35:75)
handleEvent @ controls.js:35
controls.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at WebSocket.handleEvent (controls.js:35:75)
handleEvent @ controls.js:35
```
It's not the same as of now still Open #209 because I'm getting these errors, and it's on ESP32 instead of ESP8266.
It does not matter where I try to open it. On any browser, on any device, even on a phone.
I'm not really experienced in ESP32 nor C++ so any help towards fixing that will be much appreciated.

**To Reproduce**
Build and upload example "gui.ino" code and try to open it in browser. (or any other example)

**Screenshots**
![image](https://github.com/user-attachments/assets/aaa89b8a-4446-4d9e-925a-ab1bd2f1952c)

**Additional context**
Versions of libraries
- ESPUI 2.2.4
- ArduinoJson 6.10.1
- AsyncTCP 1.1.1
- ESP Async WebServer 1.2.4

**Comment by Looki2000** [comment]
I don't know why, but after updating to ArduinoJson 7.2.0 it works. I tried it yesterday and it didn't even compile.
